INSERT INTO 
TmpMCIAA_Sales ( 
receiptNo, 
void, 
cash, 
credit, 
charge, 
giftcheck, 
othertender, 
linedisc, 
linesenior, 
evat, linepwd, 
linediplomat, 
subtotal, 
disc, 
senior, 
pwd, 
diplomat, 
vat, 
exvat, 
incvat, 
localtax, 
amusement, 
service, 
taxsale, 
notaxsale, 
taxexsale, 
taxincsale, 
zerosale, 
customercount, 
gross, 
refund, 
taxrate, 
posted, 
[memo] )

SELECT 
TmpMCIAA_Source.CollectionNumber AS receiptNo, 
IIf([IsCancelled]=True,1,0) AS void, 
Sum(IIf([IsCancelled]=True,0,TmpMCIAA_Source.TotalCash)) AS cash, 
Sum(IIf([IsCancelled]=True,0,TmpMCIAA_Source.TotalCreditCard)) AS credit, 
Sum(IIf([IsCancelled]=True,0,TmpMCIAA_Source.TotalCharge)) AS charge, 
Sum(IIf([IsCancelled]=True,0,TmpMCIAA_Source.TotalGiftCertificate)) AS giftcheck, 
Sum(IIf([IsCancelled]=True,0,TmpMCIAA_Source.TotalOtherTender)) AS othertender,  
Sum(IIf([Discount]<>"Senior Citizen Discount" And [Discount]<>"PWD",[discountamount],0)) AS linedisc, 
Sum(IIf([Discount]="Senior Citizen Discount",[discountamount],0)) AS linesenior, 
Sum(IIf([Discount]="Senior Citizen Discount",([Quantity]*[Price])-[DiscountAmount]-[Amount],0)) AS evat, 
Sum(IIf([Discount]="PWD",[discountamount],0)) AS linepwd, 
Sum(IIf([Discount]="Diplomat" OR [Discount]="Diplomat Discount",[discountamount],0)) AS linediplomat, 
Sum(IIf([Discount]="Senior Citizen Discount",([Quantity]*[Price])-[DiscountAmount],[Amount])) AS subtotal, 
Sum([discountamount]*[quantity]) AS disc, 
Sum(IIf([Discount]="Senior Citizen Discount",[Amount],0)) AS senior,
Sum(IIf([Discount]="PWD",[Amount],0)) AS pwd, 
Sum(IIf([Discount]="Diplomat" OR [Discount]="Diplomat Discount",[Amount],0)) AS diplomat, 
Sum(TmpMCIAA_Source.taxamount) AS vat, 
Sum(IIf([Tax]="VAT-EXCLUSIVE",[TaxAmount],0)) AS exvat, 
Sum(IIf([Tax]="VAT" And [Discount]<>"Senior Citizen Discount",[TaxAmount],0)) AS incvat,
Sum(IIf([Tax]="LOCAL-TAX",[TaxAmount],0)) AS localtax,  
Sum(IIf([Tax]="AMUSEMENT",[TaxAmount],0)) AS amusement, 
Sum(TmpMCIAA_Source.ServiceCharge) AS service, 
Sum(IIf([taxrate]>0,[amount],0)) AS taxsale, 
Sum(IIf([taxrate]=0,[amount],0)) AS notaxsale, 
Sum(0) AS taxexsale, 
Sum(IIf([taxrate]=0 And [IsCancelled]=False,0,[amount])) AS taxincsale, 
Sum(0) AS zerosale, 
1 AS customercount, 
Sum(TmpMCIAA_Source.GrossAmount) AS gross, 
Sum(TmpMCIAA_Source.TotalRefund) AS refund, 
TmpMCIAA_Source.taxrate AS taxrate, 
Format(Now(),"yyyymmddhhnnss") AS posted, "" AS [memo]
FROM TmpMCIAA_Source
GROUP BY TmpMCIAA_Source.CollectionNumber, 
IIf([IsCancelled]=True,1,0), 1, 
TmpMCIAA_Source.taxrate, "", "";
