INSERT INTO TmpRLC (
    TenantId, 
    TerminalNumber, 
    GrossAmount, 
    TaxAmount, 
    VoidAmount, 
    VoidTransaction,
    LineDiscountAmount, 
    DiscountTransaction, 
    ReturnAmount, 
    ReturnTransaction, 
    AdjustmentAmount, 
    AdjustmentTransaction, 
    ServiceChargeAmount, 
    PreviousEOD, 
    PreviousAmount, 
    CurrentEOD, 
    CurrentEODAmount, 
    TransactionDate, 
    NoveltyItemAmount, 
    MiscItemAmount, 
    LocalTax, 
    CreditSalesAmount, 
    CreditTaxAmount, 
    NonVATSalesAmount, 
    PharmaItemSalesAmount, 
    NonPharmaItemSalesAmount, 
    DisabilityDiscount, 
    GrossSalesAmountNotSubjectToPercentageRent, 
    RePrintedAmount, 
    RePrintedTransaction
)

SELECT 
    DFirst("RLC_TenantId", "SysCurrent") AS [TenantId], 
    "00000000000000" & Right([TerminalId], 2) AS [TerminalNumber], 
    Nz(Sum(GrossAmount), 0) AS GrossSalesAmount, 
    Nz(Sum(TaxAmount), 0) AS VAT, 
    Nz(Sum(IIf([IsCancelled] = -1, [Amount], 0)), 0) AS VoidAmount, 

    Nz(Sum(IIf([IsCancelled] = -1, 1, 0)), 0) AS VoidTransaction, 
    Nz(Sum(IIf([Discount] <> "Senior Citizen Discount" And [Discount] <> "PWD", [DiscountAmount], 0)), 0) AS LineDiscountAmount,
    Nz(Sum(IIf([Discount] <> "Senior Citizen Discount" And [Discount] <> "PWD" AND (Nz([DiscountAmount], 0) > 0), 1, 0)), 0) AS LineDiscountTransaction,
    
    Nz(Sum(TotalRefund), 0) AS [ReturnAmount], 

    Nz(Sum(IIF(TotalRefund>0,1,0)), 0) AS [ReturnTransaction], 
    Nz(Sum(IIf([Discount] = "Senior Citizen Discount", [DiscountAmount], 0)), 0) AS [AdjustmentAmount], 
    Nz(Sum(IIf([Discount] = "Senior Citizen Discount" AND (Nz([DiscountAmount], 0) > 0), 1, 0)), 0) AS [AdjustmentTransaction], 
    Nz(Sum(ServiceCharge), 0) AS [ServiceChargeAmount], 
    0 AS [PreviousEOD],
    0 AS [PreviousAmount], 
    0 AS [CurrentEOD], 
    0 AS [CurrentEODAmount],
    FORMAT([CollectionDate], 'MM/dd/yyyy') AS [TransactionDate], 
    0 AS [NoveltyItemAmount], 
    0 AS [MiscItemAmount],
    Nz(Sum(IIf([Tax] = "LOCAL-TAX", [TaxAmount], 0)), 0) AS [LocalTax],  
    Nz(Sum(IIf([IsCancelled] = True, 0, [TotalCreditCard])), 0) AS [CreditSalesAmount], 
    Nz(Sum(IIf([IsCancelled] = True, 0, (([TotalCreditCard] / 1.2) * 0.12))), 0) AS [CreditTaxAmount],
    Nz(Sum(IIf([TaxRate] = 0, [Amount], 0)), 0) AS [NonVATSalesAmount], 
    0 AS [PharmaItemSalesAmount], 
    0 AS [NonPharmaItemSalesAmount], 
    Nz(Sum(IIf([Discount] = "PWD", [DiscountAmount], 0)), 0) AS [DisabilityDiscount], 
    Nz(Sum(IIf([IsCancelled] = False AND ([ItemId] = 4), 0, [Amount])), 0) AS [GrossSalesAmountNotSubjectToPercentageRent],
    0 AS [RePrintedAmount],
    0 AS [RePrintedTransaction]
FROM TmpMCIAA_Source
GROUP BY 
    DFirst("RLC_TenantId", "SysCurrent"),
    "00000000000000" & Right([TerminalId], 2),
    FORMAT([CollectionDate], 'MM/dd/yyyy')
