INSERT INTO TmpRLCTotal (
    TenantId, 
    TerminalNumber, 
    GrossAmount, 
    TaxAmount, 
    VoidAmount, 
    VoidTransaction,
    DiscountAmount, 
    DiscountTransaction, 
    ReturnAmount, 
    ReturnTransaction, 
    AdjustmentAmount, 
    AdjustmentTransaction, 
    ServiceChargeAmount, 
    PreviousEOD, 
    PreviousAmount, 
    CurrentEOD, 
    CurrentEODAmount, 
    TransactionDate, 
    NoveltyItemAmount, 
    MiscItemAmount, 
    LocalTax, 
    CreditSalesAmount, 
    CreditTaxAmount, 
    NonVATSalesAmount, 
    PharmaItemSalesAmount, 
    NonPharmaItemSalesAmount, 
    DisabilityDiscount, 
    GrossSalesAmountNotSubectToPercentageRent, 
    RePrintedAmount, 
    RePrintedTransaction
)
SELECT 
    [TmpRLC].[TenantId],
    [TmpRLC].[TerminalNumber],
    FORMAT(MAX([TmpRLC].[GrossAmount]), '0.00') AS [GrossAmount],
    FORMAT(MAX([TmpRLC].[TaxAmount]), '0.00') AS [TaxAmount],
    FORMAT(SUM([TmpRLC].[VoidAmount]), '0.00') AS [VoidAmount],
    SUM([TmpRLC].[VoidTransaction]) AS [VoidTransaction],
    FORMAT(SUM([TmpRLC].[DiscountAmount]), '0.00') AS [DiscountAmount],
    SUM([TmpRLC].[DiscountTransaction]) AS [DiscountTransaction],
    FORMAT(MAX([TmpRLC].[ReturnAmount]), '0.00') AS [ReturnAmount],
    MAX([TmpRLC].[ReturnTransaction]) AS [ReturnTransaction],
    FORMAT(SUM([TmpRLC].[AdjustmentAmount]), '0.00') AS [AdjustmentAmount], 
    SUM([TmpRLC].[AdjustmentTransaction]) AS [AdjustmentTransaction], 
    FORMAT(SUM([TmpRLC].[ServiceChargeAmount]), '0.00') AS [ServiceChargeAmount],
    MAX([TmpRLC].[PreviousEOD]) AS [PreviousEOD], 
    SUM([TmpRLC].[PreviousAmount]) AS [PreviousAmount], 
    MAX([TmpRLC].[CurrentEOD]) AS [CurrentEOD], 
    FORMAT(MAX([TmpRLC].[CurrentEODAmount]) , '0.00') AS [CurrentEODAmount],
    [TmpRLC].[TransactionDate] AS [TransactionDate],
    0 AS [NoveltyItemAmount],
    0 AS [MiscItemAmount],
    FORMAT(SUM([TmpRLC].[LocalTax]), '0.00') AS [LocalTax],
    FORMAT(SUM([TmpRLC].[CreditSalesAmount]), '0.00') AS [CreditSalesAmount],
    FORMAT(((SUM([TmpRLC].[CreditSalesAmount]))/1.12)*0.12, '0.00') AS [CreditTaxAmount],
    FORMAT(SUM([TmpRLC].[NonVATSalesAmount]), '0.00') AS [NonVATSalesAmount],
    0 AS [PharmaItemSalesAmount],
    0 AS [NonPharmaItemSalesAmount],
    FORMAT(SUM([TmpRLC].[DisabilityDiscount]), '0.00') AS [DisabilityDiscount],
    SUM([TmpRLC].[GrossSalesAmountNotSubectToPercentageRent]) AS [GrossSalesAmountNotSubectToPercentageRent],
    SUM([TmpRLC].[RePrintedAmount]) AS [RePrintedAmount], 
    SUM([TmpRLC].[RePrintedTransaction]) AS [RePrintedTransaction]
FROM 
    TmpRLC

GROUP BY
    [TmpRLC].[TenantId],
    [TmpRLC].[TerminalNumber],
    [TmpRLC].[TransactionDate]
