INSERT INTO TmpMCIAA_Summary (
    [salesDate], 
    [zcounter], 
    [previousnrgt], 
    [nrgt], 
    [previoustax], 
    [newtax], 
    [previoustaxsale], 
    [newtaxsale], 
    [prevousnotaxsale], 
    [newnotaxsale], 
    [opentime], 
    [closetime], 
    [gross], 
    [vat], 
    [localtax], 
    [amusement], 
    [taxsale], 
    [notaxsale], 
    [zerosale], 
    [void], 
    [voidcnt], 
    [disc], 
    [disccnt], 
    [refund], 
    [refundcnt], 
    [senior], 
    [seniorcnt], 
    [pwd], 
    [pwdcnt], 
    [diplomat], 
    [diplomatcnt], 
    [service], 
    [servicecnt], 
    [receiptstart], 
    [receiptend], 
    [trxcnt], 
    [cash], 
    [cashcnt], 
    [credit], 
    [creditcnt], 
    [charge], 
    [chargecnt], 
    [giftcheck], 
    [giftcheckcnt], 
    [othertender], 
    [othertendercnt] )

SELECT
[TmpMCIAA_Sales].[salesDate] AS [salesDate],
1 AS [zcounter],
0 AS [previousnrgt], 
SUM([TmpMCIAA_Sales].[nrgt]) AS [nrgt], 
0 AS [previoustax], 
SUM([TmpMCIAA_Sales].[vat]) AS [newtax],
0 AS [previoustaxsale], 
SUM([TmpMCIAA_Sales].[taxsale]) AS [newtaxsale],
0 AS [prevousnotaxsale], 
SUM([TmpMCIAA_Sales].[notaxsale]) AS [newnotaxsale],
MIN([TmpMCIAA_Sales].[LineTimeStamp]) AS [opentime], 
MAX([TmpMCIAA_Sales].[LineTimeStamp]) AS [closetime], 
SUM([TmpMCIAA_Sales].[gross]) AS [gross],
SUM([TmpMCIAA_Sales].[vat]) AS [vat],
SUM([TmpMCIAA_Sales].[localtax]) AS [localtax],
SUM([TmpMCIAA_Sales].[amusement]) AS [amusement],
SUM([TmpMCIAA_Sales].[taxsale]) AS [taxsale],
SUM([TmpMCIAA_Sales].[notaxsale]) AS [notaxsale],
0 AS [zerosale],
SUM([TmpMCIAA_Sales].[voidamount]) AS [void],
SUM([TmpMCIAA_Sales].[void]) AS [voidcnt],
SUM([TmpMCIAA_Sales].[linedisc]) AS [disc],
SUM([TmpMCIAA_Sales].[linedisccnt]) AS [disccnt],
SUM([TmpMCIAA_Sales].[refund]) AS [refund],
SUM([TmpMCIAA_Sales].[refundcnt]) AS [refundcnt],
SUM([TmpMCIAA_Sales].[linesenior]) AS [senior],
SUM([TmpMCIAA_Sales].[lineseniorcnt]) AS [seniorcnt],
SUM([TmpMCIAA_Sales].[linepwd]) AS [pwd],
SUM([TmpMCIAA_Sales].[linepwdcnt]) AS [pwdcnt],
SUM([TmpMCIAA_Sales].[linediplomat]) AS [diplomat],
SUM([TmpMCIAA_Sales].[linediplomatcnt]) AS [diplomatcnt],
SUM([TmpMCIAA_Sales].[service]) AS [service],
SUM([TmpMCIAA_Sales].[servicecnt]) AS [servicecnt],
MIN([TmpMCIAA_Sales].[receiptNo]) AS [receiptstart], 
MAX([TmpMCIAA_Sales].[receiptNo]) AS [receiptend], 
DCount("receiptNo","TmpMCIAA_Sales","Void=0") AS [trxcnt],
SUM([TmpMCIAA_Sales].[cash]) AS [cash],
SUM([TmpMCIAA_Sales].[cashcnt]) AS [cashcnt],
SUM([TmpMCIAA_Sales].[credit]) AS [credit],
SUM([TmpMCIAA_Sales].[creditcnt]) AS [creditcnt],
0 AS [charge], 
0 AS [chargecnt],
SUM([TmpMCIAA_Sales].[giftcheck]) AS [giftcheck],
SUM([TmpMCIAA_Sales].[giftcheckcnt]) AS [giftcheckcnt],
SUM([TmpMCIAA_Sales].[othertender]) AS [othertender],
SUM([TmpMCIAA_Sales].[othertendercnt]) AS [othertendercnt]
FROM [TmpMCIAA_Sales]
GROUP BY 
[TmpMCIAA_Sales].[salesDate],
DCount("receiptNo","TmpMCIAA_Sales","Void=0") 